In [1]:
import pandas as pd

# Read CSV file into a DataFrame
df = pd.read_csv('/gpfs/data1/vclgp/xiongl/HeightComparisonGEDI_IS2_IS1/Out/is1_global_0dot125degree_gridded.csv')

In [2]:
# Display the DataFrame
print(df)

              x        y      layer
0       88.3125  75.0625   3.234000
1       88.3125  74.9375   3.783667
2       88.4375  74.9375   4.326320
3       88.9375  74.9375  14.455000
4       89.0625  74.9375  10.787000
...         ...      ...        ...
220349 -67.3125 -55.0625  11.215818
220350 -66.4375 -55.0625   8.573000
220351 -67.9375 -55.1875  15.288143
220352 -67.3125 -55.1875   7.076333
220353 -67.3125 -55.6875  13.712000

[220354 rows x 3 columns]

In [6]:
# Loop through every row
for index, row in df.head(100).iterrows():
    # Access row values using column names or indices
    col1 = row['x']
    col2 = row['y']
    
    # Perform operations on row data
    # ...
    
    # Print row information
    print(f"Row index: {index}")
    print(f"Column 1 value: {col1}")
    print(f"Column 2 value: {col2}")
    print("")

Row index: 0
Column 1 value: 88.3125
Column 2 value: 75.0625

Row index: 1
Column 1 value: 88.3125
Column 2 value: 74.9375

Row index: 2
Column 1 value: 88.4375
Column 2 value: 74.9375

Row index: 3
Column 1 value: 88.9375
Column 2 value: 74.9375

Row index: 4
Column 1 value: 89.0625
Column 2 value: 74.9375

Row index: 5
Column 1 value: 89.1875
Column 2 value: 74.9375

Row index: 6
Column 1 value: 89.9375
Column 2 value: 74.9375

Row index: 7
Column 1 value: 90.5625
Column 2 value: 74.9375

Row index: 8
Column 1 value: 90.6875
Column 2 value: 74.9375

Row index: 9
Column 1 value: 91.0625
Column 2 value: 74.9375

Row index: 10
Column 1 value: 91.1875
Column 2 value: 74.9375

Row index: 11
Column 1 value: 91.5625
Column 2 value: 74.9375

Row index: 12
Column 1 value: 92.8125
Column 2 value: 74.9375

Row index: 13
Column 1 value: 92.9375
Column 2 value: 74.9375

Row index: 14
Column 1 value: 93.4375
Column 2 value: 74.9375

Row index: 15
Column 1 value: 93.6875
Column 2 value: 74.9375

Row index: 16
Column 1 value: 93.9375
Column 2 value: 74.9375

Row index: 17
Column 1 value: 94.0625
Column 2 value: 74.9375

Row index: 18
Column 1 value: 94.8125
Column 2 value: 74.9375

Row index: 19
Column 1 value: 94.9375
Column 2 value: 74.9375

Row index: 20
Column 1 value: 95.0625
Column 2 value: 74.9375

Row index: 21
Column 1 value: 95.5625
Column 2 value: 74.9375

Row index: 22
Column 1 value: 95.6875
Column 2 value: 74.9375

Row index: 23
Column 1 value: 96.9375
Column 2 value: 74.9375

Row index: 24
Column 1 value: 98.5625
Column 2 value: 74.9375

Row index: 25
Column 1 value: 98.6875
Column 2 value: 74.9375

Row index: 26
Column 1 value: 98.8125
Column 2 value: 74.9375

Row index: 27
Column 1 value: 99.3125
Column 2 value: 74.9375

Row index: 28
Column 1 value: 99.5625
Column 2 value: 74.9375

Row index: 29
Column 1 value: 100.3125
Column 2 value: 74.9375

Row index: 30
Column 1 value: 101.5625
Column 2 value: 74.9375

Row index: 31
Column 1 value: 101.6875
Column 2 value: 74.9375

Row index: 32
Column 1 value: 102.4375
Column 2 value: 74.9375

Row index: 33
Column 1 value: 102.8125
Column 2 value: 74.9375

Row index: 34
Column 1 value: 103.3125
Column 2 value: 74.9375

Row index: 35
Column 1 value: 103.6875
Column 2 value: 74.9375

Row index: 36
Column 1 value: 105.1875
Column 2 value: 74.9375

Row index: 37
Column 1 value: 105.3125
Column 2 value: 74.9375

Row index: 38
Column 1 value: 105.6875
Column 2 value: 74.9375

Row index: 39
Column 1 value: 105.8125
Column 2 value: 74.9375

Row index: 40
Column 1 value: 105.9375
Column 2 value: 74.9375

Row index: 41
Column 1 value: 106.0625
Column 2 value: 74.9375

Row index: 42
Column 1 value: 106.1875
Column 2 value: 74.9375

Row index: 43
Column 1 value: 106.3125
Column 2 value: 74.9375

Row index: 44
Column 1 value: 106.6875
Column 2 value: 74.9375

Row index: 45
Column 1 value: 106.8125
Column 2 value: 74.9375

Row index: 46
Column 1 value: 107.3125
Column 2 value: 74.9375

Row index: 47
Column 1 value: 107.4375
Column 2 value: 74.9375

Row index: 48
Column 1 value: 107.5625
Column 2 value: 74.9375

Row index: 49
Column 1 value: 108.0625
Column 2 value: 74.9375

Row index: 50
Column 1 value: 108.1875
Column 2 value: 74.9375

Row index: 51
Column 1 value: 108.3125
Column 2 value: 74.9375

Row index: 52
Column 1 value: 108.8125
Column 2 value: 74.9375

Row index: 53
Column 1 value: 108.9375
Column 2 value: 74.9375

Row index: 54
Column 1 value: 109.5625
Column 2 value: 74.9375

Row index: 55
Column 1 value: 109.6875
Column 2 value: 74.9375

Row index: 56
Column 1 value: 110.1875
Column 2 value: 74.9375

Row index: 57
Column 1 value: 110.5625
Column 2 value: 74.9375

Row index: 58
Column 1 value: 111.0625
Column 2 value: 74.9375

Row index: 59
Column 1 value: 111.1875
Column 2 value: 74.9375

Row index: 60
Column 1 value: 111.3125
Column 2 value: 74.9375

Row index: 61
Column 1 value: 111.8125
Column 2 value: 74.9375

Row index: 62
Column 1 value: 111.9375
Column 2 value: 74.9375

Row index: 63
Column 1 value: 112.0625
Column 2 value: 74.9375

Row index: 64
Column 1 value: 112.3125
Column 2 value: 74.9375

Row index: 65
Column 1 value: 112.4375
Column 2 value: 74.9375

Row index: 66
Column 1 value: 112.5625
Column 2 value: 74.9375

Row index: 67
Column 1 value: 149.9375
Column 2 value: 74.9375

Row index: 68
Column 1 value: 150.0625
Column 2 value: 74.9375

Row index: 69
Column 1 value: 87.4375
Column 2 value: 74.8125

Row index: 70
Column 1 value: 87.5625
Column 2 value: 74.8125

Row index: 71
Column 1 value: 88.4375
Column 2 value: 74.8125

Row index: 72
Column 1 value: 88.5625
Column 2 value: 74.8125

Row index: 73
Column 1 value: 88.6875
Column 2 value: 74.8125

Row index: 74
Column 1 value: 88.8125
Column 2 value: 74.8125

Row index: 75
Column 1 value: 89.3125
Column 2 value: 74.8125

Row index: 76
Column 1 value: 89.4375
Column 2 value: 74.8125

Row index: 77
Column 1 value: 89.5625
Column 2 value: 74.8125

Row index: 78
Column 1 value: 90.0625
Column 2 value: 74.8125

Row index: 79
Column 1 value: 90.1875
Column 2 value: 74.8125

Row index: 80
Column 1 value: 90.4375
Column 2 value: 74.8125

Row index: 81
Column 1 value: 90.9375
Column 2 value: 74.8125

Row index: 82
Column 1 value: 91.0625
Column 2 value: 74.8125

Row index: 83
Column 1 value: 91.5625
Column 2 value: 74.8125

Row index: 84
Column 1 value: 91.6875
Column 2 value: 74.8125

Row index: 85
Column 1 value: 91.8125
Column 2 value: 74.8125

Row index: 86
Column 1 value: 92.1875
Column 2 value: 74.8125

Row index: 87
Column 1 value: 92.3125
Column 2 value: 74.8125

Row index: 88
Column 1 value: 93.0625
Column 2 value: 74.8125

Row index: 89
Column 1 value: 93.3125
Column 2 value: 74.8125

Row index: 90
Column 1 value: 93.4375
Column 2 value: 74.8125

Row index: 91
Column 1 value: 93.8125
Column 2 value: 74.8125

Row index: 92
Column 1 value: 93.9375
Column 2 value: 74.8125

Row index: 93
Column 1 value: 94.6875
Column 2 value: 74.8125

Row index: 94
Column 1 value: 95.0625
Column 2 value: 74.8125

Row index: 95
Column 1 value: 95.1875
Column 2 value: 74.8125

Row index: 96
Column 1 value: 95.4375
Column 2 value: 74.8125

Row index: 97
Column 1 value: 96.1875
Column 2 value: 74.8125

Row index: 98
Column 1 value: 96.3125
Column 2 value: 74.8125

Row index: 99
Column 1 value: 97.5625
Column 2 value: 74.8125